version: '3'
services:
    metrics-exporter:
        build:
            context: ../likelib-exporter
        environment: 
            CH_HOST: http://0.0.0.0:8123
            BOOTSTRAP_SERVERS: 0.0.0.0:9092
        network_mode: host
        
    api:
        build:
            context: ../api
        ports:
            - "8080:8080"
        environment:
            CLICKHOUSE_HOST: 0.0.0.0
        network_mode: host

    client:
        build:
            context: ../client
        ports:
            - "5000:5000"
        environment:
            TRANSACTIONS_API_ENDPOINT: http://localhost:8080/
        network_mode: host
        